# codemagic.yaml
# Workflow para compilar la app Voces de Esperanza (Gatsby + Capacitor) - VERSIÓN CORREGIDA

workflows:
  # --- WORKFLOW PARA ANDROID (CORREGIDO) ---
  android-build:
    name: VDE Android Build
    instance_type: mac_mini_m1
    environment:
      java: 21
      groups:
        # Esto importa correctamente TODAS las variables que creaste en la UI
        - keystore_credentials
        - contentful_credentials
      vars:
        # Solo definimos las variables que no son secretas
        PACKAGE_NAME: "com.vocesdeesperanza.app"
    scripts:
      - name: Instalar dependencias
        script: | 
          npm install
      - name: Construir el sitio Gatsby
        script: | 
          npm run build
      - name: Sincronizar con Capacitor y actualizar Android
        script: | 
          npx cap sync android
          npx cap update android
      
      # --- PASO NUEVO Y CRUCIAL ---
      - name: Decodificar y guardar el Keystore
        script: | 
          echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.keystore
          
      - name: Construir APK de Android
        script: | 
          cd android
          # PASO CRUCIAL: Damos permisos de ejecución al script de Gradle
          chmod +x ./gradlew 
          # Ahora sí, el comando funcionará sin problemas
          ./gradlew assembleRelease 
    artifacts:
      - android/app/build/outputs/**/*.apk

  # codemagic.yaml
# Workflow para compilar la app Voces de Esperanza (Gatsby + Capacitor)

workflows:
  # --- WORKFLOW PARA ANDROID ---
  android-build:
    name: VDE Android Build
    instance_type: mac_mini_m1
    environment:
      java: 21
      groups:
        - keystore_credentials
        - contentful_credentials
      vars:
        PACKAGE_NAME: "com.vocesdeesperanza.app"
    scripts:
      - name: Instalar dependencias
        script: | 
          npm install
      - name: Construir el sitio Gatsby
        script: | 
          npm run build
      - name: Sincronizar con Capacitor y actualizar Android
        script: | 
          npx cap sync android
          npx cap update android
      - name: Decodificar y guardar el Keystore
        script: | 
          echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.keystore
      - name: Construir AAB de Android
        script: | 
          cd android
          chmod +x ./gradlew 
          ./gradlew bundleRelease 
    artifacts:
      - android/app/build/outputs/**/*.aab

  # --- WORKFLOW PARA iOS (CON PUBLICACIÓN CORREGIDA) ---
  ios-build:
    name: VDE iOS Build
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: VDE_AppStoreConnect
    environment:
      groups:
        - app_store_connect_credentials
        - contentful_credentials
      vars:
        XCODE_TEAM_ID: AKKP464BSH
        XCODE_BUNDLE_ID: com.vocesdeesperanza.app
    scripts:
      - name: Instalar dependencias
        script: | 
          npm install
      - name: Instalar dependencias de iOS (Cocoapods)
        script: | 
          cd ios/App && pod install
      - name: Construir el sitio Gatsby
        script: | 
          npm run build
      - name: Sincronizar con Capacitor y actualizar iOS
        script: | 
          npx cap sync ios
          npx cap update ios
      - name: Inicializar Llavero y Añadir Certificados
        script: |
          keychain initialize
          keychain add-certificates
      - name: Forzar Firma Automática en el Proyecto Xcode
        script: |
          set -ex
          PROJECT_FILE="ios/App/App.xcodeproj/project.pbxproj"
          sed -i.bak -e 's/PROVISIONING_PROFILE_SPECIFIER = ".*";/PROVISIONING_PROFILE_SPECIFIER = "";/' "$PROJECT_FILE"
          sed -i.bak -e 's/CODE_SIGN_STYLE = Manual;/CODE_SIGN_STYLE = Automatic;/' "$PROJECT_FILE"
          sed -i.bak -e "s/DEVELOPMENT_TEAM = .*;/DEVELOPMENT_TEAM = $XCODE_TEAM_ID;/" "$PROJECT_FILE"
      - name: Construir y archivar con xcodebuild
        script: | 
          set -ex
          xcodebuild archive \
            -workspace "ios/App/App.xcworkspace" \
            -scheme "App" \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            -allowProvisioningUpdates
      - name: Exportar el .ipa
        script: |
          set -ex
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            -exportPath "$CM_OUTPUT_DIR" \
            -exportOptionsPlist "export_options.plist"
    artifacts:
      - $CM_OUTPUT_DIR/*.ipa
    publishing:
      app_store_connect:
        api_key: $CM_API_KEY
        key_id: $CM_KEY_ID
        issuer_id: $CM_ISSUER_ID
        submit_to_testflight: true