# codemagic.yaml
# Workflow para compilar la app Voces de Esperanza (Gatsby + Capacitor) - VERSIÓN CORREGIDA

workflows:
  # --- WORKFLOW PARA ANDROID (CORREGIDO) ---
  android-build:
    name: VDE Android Build
    instance_type: mac_mini_m1
    environment:
      groups:
        # Esto importa correctamente TODAS las variables que creaste en la UI
        - keystore_credentials
        - contentful_credentials
      vars:
        # Solo definimos las variables que no son secretas
        PACKAGE_NAME: "com.vocesdeesperanza.app"
    scripts:
      - name: Instalar dependencias
        script: | 
          npm install
      - name: Construir el sitio Gatsby
        script: | 
          npm run build
      - name: Sincronizar con Capacitor y actualizar Android
        script: | 
          npx cap sync android
          npx cap update android
      
      # --- PASO NUEVO Y CRUCIAL ---
      - name: Decodificar y guardar el Keystore
        script: | 
          echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.keystore
          
      - name: Construir AAB de Android
        script: | 
          cd android
          # Este comando ahora encontrará el keystore que creamos en el paso anterior
          ./gradlew bundleRelease 
    artifacts:
      - android/app/build/outputs/**/*.aab

  # --- WORKFLOW PARA iOS (SIN CAMBIOS, YA ESTABA BIEN) ---
  ios-build:
    name: VDE iOS Build
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: VDE_AppStoreConnect # Reemplaza con el nombre de tu integración
    environment:
      groups:
        - app_store_connect_credentials
        - contentful_credentials 
      vars:
        XCODE_WORKSPACE: "App.xcworkspace" 
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.vocesdeesperanza.app"
    scripts:
      - name: Instalar dependencias
        script: | 
          npm install
      - name: Instalar dependencias de iOS (Cocoapods)
        script: | 
          cd ios/App && pod install
      - name: Construir el sitio Gatsby
        script: | 
          npm run build
      - name: Sincronizar con Capacitor y actualizar iOS
        script: | 
          npx cap sync ios
          npx cap update ios
      - name: Configurar firma de código para iOS
        script: | 
          xcode-project use-profiles
      - name: Construir IPA de iOS
        script: | 
          xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*
    publishing:
      app_store_connect:
        api_key: $CM_API_KEY
        key_id: $CM_KEY_ID
        issuer_id: $CM_ISSUER_ID
        submit_to_testflight: true
        beta_groups:
          - "Amigos y Familia"
          - "Equipo de Ministerio"