# codemagic.yaml
# Workflow para compilar la app Voces de Esperanza (Gatsby + Capacitor) - VERSIÓN CORREGIDA

workflows:
  # --- WORKFLOW PARA ANDROID (CORREGIDO) ---
  android-build:
    name: VDE Android Build
    instance_type: mac_mini_m1
    environment:
      java: 21
      groups:
        # Esto importa correctamente TODAS las variables que creaste en la UI
        - keystore_credentials
        - contentful_credentials
        - firebase_credentials
      vars:
        # Solo definimos las variables que no son secretas
        PACKAGE_NAME: "com.vocesdeesperanza.app"
        CM_KEYSTORE_PATH: /tmp/keystore.keystore
    scripts:
      - name: Instalar dependencias
        script: | 
          npm install
      - name: Construir el sitio Gatsby
        script: | 
          # Cambia 'npm run build' por 'npm run build:mobile'
          npm run build:mobile
      - name: Decodificar google-services.json
        script: |
          echo $GOOGLE_SERVICES_JSON | base64 --decode > android/app/google-services.json

      - name: Sincronizar con Capacitor y actualizar Android
        script: |
          npx cap sync android
          npx cap update android

      # --- PASO NUEVO Y CRUCIAL ---
      - name: Decodificar y guardar el Keystore
        script: |
          echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.keystore
          
      - name: Construir AAB de Android
        script: | 
          cd android
          # PASO CRUCIAL: Damos permisos de ejecución al script de Gradle
          chmod +x ./gradlew 
          # Construir Android App Bundle (AAB) en lugar de APK
          ./gradlew bundleRelease 
    artifacts:
      - android/app/build/outputs/**/*.aab


   # --- WORKFLOW PARA iOS (SOLUCIÓN FINAL DE CLAUDE #2) ---
  ios-build:
    name: VDE iOS Build
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: VDE_AppStoreConnect
    environment:
      groups:
        - app_store_connect_credentials
        - contentful_credentials
        - ios_signing_credentials
        - firebase_credentials
      vars:
        XCODE_TEAM_ID: AKKP464BSH
        KEYCHAIN_PATH: $CM_KEYCHAIN_PATH
        KEYCHAIN_PASSWORD: $CM_KEYCHAIN_PASSWORD
    scripts:
      - name: Instalar dependencias
        script: | 
          npm install
      - name: Instalar dependencias de iOS (Cocoapods)
        script: | 
          cd ios/App && pod install
      - name: Construir el sitio Gatsby
        script: |
          # Cambia 'npm run build' por 'npm run build:mobile'
          npm run build:mobile

      - name: Decodificar GoogleService-Info.plist
        script: |
          echo $GOOGLE_SERVICE_INFO_PLIST | base64 --decode > ios/App/App/GoogleService-Info.plist

      - name: Sincronizar con Capacitor y actualizar iOS
        script: |
          npx cap sync ios
          npx cap update ios
      - name: Configurar Llavero y Perfil de Aprovisionamiento
        script: |
          set -ex
          echo $CERTIFICATE_P12_BASE64 | base64 --decode > /tmp/certificate.p12
          
          # Create keychain with a simpler path
          KEYCHAIN_PATH="$HOME/Library/Keychains/temp.keychain"
          KEYCHAIN_PASSWORD="temp_password_123"
          
          security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security set-keychain-settings -t 3600 -l "$KEYCHAIN_PATH"
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security import /tmp/certificate.p12 -k "$KEYCHAIN_PATH" -P "$P12_PASSWORD" -A -t cert -f pkcs12
          security set-key-partition-list -S apple-tool:,apple: -s -k "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security list-keychains -d user -s "$KEYCHAIN_PATH" $(security list-keychains -d user | sed s/\"//g)
          
          # Export for later use
          echo "export KEYCHAIN_PATH=\"$KEYCHAIN_PATH\"" >> $CM_ENV
          echo "export KEYCHAIN_PASSWORD=\"$KEYCHAIN_PASSWORD\"" >> $CM_ENV
          
          PROFILE_PATH=~/Library/MobileDevice/Provisioning\ Profiles
          mkdir -p "$PROFILE_PATH"
          echo $PROVISIONING_PROFILE_BASE64 | base64 --decode > "$PROFILE_PATH/VDE_AppStore_Profile.mobileprovision"
          
      - name: Construir y Archivar (Firma Dirigida por SDK)
        script: |
          set -ex
          # Source the environment to get keychain variables
          source $CM_ENV

          # Navigate to project directory
          cd ios/App

          # Configure the App target settings in xcodeproj
          # This is a more precise approach using PlistBuddy
          PROJECT_FILE="App.xcodeproj/project.pbxproj"

          # Backup the original file
          cp "$PROJECT_FILE" "$PROJECT_FILE.backup"

          # Use sed to modify ONLY the App target build settings
          # We look for the App NativeTarget section and modify only within it
          
          # 1. Update CODE_SIGN_STYLE to Manual ONLY inside the App NativeTarget configurations
          perl -i -pe 'BEGIN{undef $/;} s/(isa = PBXNativeTarget;[^}]*name = App;[^}]*buildConfigurationList = )([0-9A-F]+)( \/\* Build configuration list for PBXNativeTarget "App" \*\/;)/$1$2$3/g' "$PROJECT_FILE"
          
          # Getting the ID of the BuildConfigurationList for App
          CONFIG_LIST_ID=$(grep -A 20 "isa = PBXNativeTarget;" "$PROJECT_FILE" | grep -A 5 "name = App;" | grep "buildConfigurationList =" | awk '{print $3}')
          
          # Now find the build configurations in that list (Debug/Release IDs)
          # This is getting complicated with shell/sed. A safer "brute force" but limited scope is better:
          
          # Alternative safer sed: Match the specific lines we saw in your project file.
          # We saw that the App target configs are named "Debug" and "Release" inside XCBuildConfiguration section
          # But Pods also have Debug/Release.
          
          # Let simple sed do it but ONLY if we are careful.
          # The "Invalid Binary" is likely due to Pods being forced to Manual without profile.
          
          # BETTER APPROACH: Do NOT force Manual signing in project file.
          # Allow xcodebuild to handle it via the command line arguments provided:
          # CODE_SIGN_IDENTITY="Apple Distribution"
          # OTHER_CODE_SIGN_FLAGS="--keychain ..."
          # PROVISIONING_PROFILE_SPECIFIER (added via flag instead of project modification)
          
          # So we will REMOVE the potentially destructive sed commands and pass PROVISIONING_PROFILE_SPECIFIER to xcodebuild directly.
          
          # 1. Update CODE_SIGN_STYLE to Manual and add settings ONLY for App Target (Release ID: 504EC3181FED79650016851F)
          # We use the specific ID found in your project.pbxproj to avoid affecting Pods
          
          # For Release Configuration (App Target)
          sed -i '' '/504EC3181FED79650016851F.*Release/,/}/ s/CODE_SIGN_STYLE = Automatic;/CODE_SIGN_STYLE = Manual;/' "$PROJECT_FILE"
          
          # Add Provisioning Profile and Entitlements to Release
          sed -i '' '/504EC3181FED79650016851F.*Release/,/}/ s/CODE_SIGN_STYLE = Manual;/CODE_SIGN_STYLE = Manual;\
                PROVISIONING_PROFILE_SPECIFIER = "VDE AppStore Profile";\
                CODE_SIGN_ENTITLEMENTS = App\/App.entitlements;/' "$PROJECT_FILE"

          # Go back to build directory
          cd ../..

          # Unlock keychain before building
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"

          # Now build
          xcodebuild archive \
            -workspace "ios/App/App.xcworkspace" \
            -scheme "App" \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            -configuration Release \
            DEVELOPMENT_TEAM="$XCODE_TEAM_ID" \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            OTHER_CODE_SIGN_FLAGS="--keychain \"$KEYCHAIN_PATH\""
            
      - name: Exportar el .ipa (Modo Manual)
        script: |
          set -ex
          # Create output directory if it doesn't exist
          mkdir -p "$CM_BUILD_DIR/output"
          
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            -exportPath "$CM_BUILD_DIR/output" \
            -exportOptionsPlist "export_options.plist"
    artifacts:
      - $CM_BUILD_DIR/output/*.ipa
    publishing:
      app_store_connect:
        # Usamos los nombres de variables que definiste en la UI de Codemagic
        api_key: $CM_API_KEY
        key_id: $CM_KEY_ID
        issuer_id: $CM_ISSUER_ID
        submit_to_testflight: true