# codemagic.yaml
# Workflow para compilar la app Voces de Esperanza (Gatsby + Capacitor)

workflows:
  # --- WORKFLOW PARA ANDROID ---
  android-build:
    name: VDE Android Build
    instance_type: mac_mini_m1 # Usamos M1 para velocidad
    environment:
      # Variables de entorno para la firma de Android.
      # Sube tu keystore a Codemagic y configura estas variables en la UI.
      # https://docs.codemagic.io/yaml-code-signing/android-code-signing/
      groups:
        - keystore_credentials 
      vars:
        # Asegúrate de que estos nombres coincidan con los de Codemagic
        CM_KEYSTORE_PATH: /tmp/keystore.keystore
        CM_KEYSTORE: Encrypted(...) 
        CM_KEYSTORE_PASSWORD: Encrypted(...)
        CM_KEY_ALIAS: Encrypted(...)
        CM_KEY_PASSWORD: Encrypted(...)
        PACKAGE_NAME: "com.vocesdeesperanza.app"
    scripts:
      - name: Instalar dependencias
        script: | 
          npm install
      - name: Construir el sitio Gatsby
        script: | 
          # Este es tu script para compilar la webapp
          npm run build
      - name: Sincronizar con Capacitor y actualizar Android
        script: | 
          npx cap sync android
          npx cap update android
      - name: Construir APK/AAB de Android
        script: | 
          cd android
          # Limpia builds anteriores y construye el Android App Bundle (AAB) para la Play Store
          ./gradlew bundleRelease 
    artifacts:
      - android/app/build/outputs/**/*.aab # Recolecta el AAB final

  # --- WORKFLOW PARA iOS ---
  ios-build:
    name: VDE iOS Build
    instance_type: mac_mini_m1
    integrations:
      # Conecta tu cuenta de Apple Developer en la UI de Codemagic
      app_store_connect: VDE_AppStoreConnect # Reemplaza con el nombre de tu integración
    environment:
      groups:
        # Grupo para las variables de App Store Connect
        - app_store_connect_credentials 
      vars:
        XCODE_WORKSPACE: "App.xcworkspace" 
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.vocesdeesperanza.app"
    scripts:
      - name: Instalar dependencias
        script: | 
          npm install
      - name: Instalar dependencias de iOS (Cocoapods)
        script: | 
          cd ios/App && pod install
      - name: Construir el sitio Gatsby
        script: | 
          npm run build
      - name: Sincronizar con Capacitor y actualizar iOS
        script: | 
          npx cap sync ios
          npx cap update ios
      - name: Configurar firma de código para iOS
        script: | 
          # Codemagic se encarga de esto automáticamente con la integración de App Store Connect
          xcode-project use-profiles
      - name: Construir IPA de iOS
        script: | 
          xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa # Recolecta el IPA final
      - /tmp/xcodebuild_logs/*
    publishing:
      # Publicación automática a TestFlight
      app_store_connect:
        api_key: $CM_API_KEY
        key_id: $CM_KEY_ID
        issuer_id: $CM_ISSUER_ID
        submit_to_testflight: true
        beta_groups: # Opcional: especifica grupos de testers
          - "Amigos y Familia"
          - "Equipo de Ministerio"